import { createFileRoute } from "@tanstack/react-router";
import previewHtml from "../../preview/palette-preview.html?raw";

/**
 * The three palette options, rendered on real screens, for the owner to choose from
 * (UX overhaul, 8 October 2026 — the owner's ruling that the current palette "is looking
 * like a black and white TV", and that the palette is the one decision only they make).
 *
 * Served as a standalone document rather than through the app shell: the preview carries
 * its own token layer, and the shell's styles would bleed into it. The source file is
 * `src/preview/palette-preview.html`, generated by the designer's audit
 * (`/home/team/shared/UX-OVERHAUL.md`, deliverable C) and imported raw so it ships with
 * the build.
 *
 *   GET /api/palette-preview  → the preview (palette A/B/C, screen: Chains or Audit)
 *
 * No auth: it renders seeded example data only, contains no live rows and no capability
 * is exercised. Remove this route once the palette is chosen and lands as tokens.
 */
export const Route = createFileRoute("/api/palette-preview")({
  server: {
    handlers: {
      GET: async () =>
        new Response(previewHtml, {
          headers: {
            "content-type": "text/html; charset=utf-8",
            "cache-control": "no-store",
          },
        }),
    },
  },
});
